# Generated by Django 5.2 on 2025-04-08 14:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0002_nomenclature_effective_date_nomenclature_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
