# Generated by Django 5.2 on 2025-04-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0003_alter_nomenclature_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='uuid',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
