# Generated by Django 5.2 on 2025-04-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0004_alter_nomenclature_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lsi',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lsi',
            name='name',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='abbreviation',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='cipher',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='drawing_number',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='ekps_code',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='internal_code',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='kvt_code',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='type_of_nomenclature',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='uuid',
        ),
        migrations.AddField(
            model_name='lsi',
            name='apikey',
            field=models.CharField(default='default_apikey', max_length=255),
        ),
        migrations.AddField(
            model_name='lsi',
            name='data',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='lsi',
            name='sender',
            field=models.CharField(default='intbus', max_length=255),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='apikey',
            field=models.CharField(default='default_apikey', max_length=255),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='data',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='sender',
            field=models.CharField(default='intbus', max_length=255),
        ),
    ]
