# Generated by Django 5.2 on 2025-04-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0005_remove_lsi_description_remove_lsi_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsi',
            name='sent_to_atom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lsi',
            name='sent_to_teamcenter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='sent_to_atom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='sent_to_teamcenter',
            field=models.BooleanField(default=False),
        ),
    ]
