# Generated by Django 5.2 on 2025-04-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0006_lsi_sent_to_atom_lsi_sent_to_teamcenter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsi',
            name='code',
            field=models.CharField(blank=True, help_text='Код объекта', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lsi',
            name='name',
            field=models.CharField(blank=True, help_text='Имя объекта, также используется как NAME в TeamCenter', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='code',
            field=models.CharField(blank=True, help_text='Код объекта', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='name',
            field=models.CharField(blank=True, help_text='Имя объекта, также используется как NAME в TeamCenter', max_length=255, null=True),
        ),
    ]
