# Generated by Django 5.2 on 2025-04-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0007_lsi_code_lsi_name_nomenclature_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCenterLSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField(default='default_apikey', max_length=255)),
                ('sender', models.CharField(default='TeamCenter', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position_name', models.CharField(help_text='Название позиции (вместо name)', max_length=255)),
                ('uuid', models.CharField(blank=True, help_text='UUID компонента', max_length=100, null=True)),
                ('drawing_number', models.CharField(blank=True, help_text='Номер чертежа', max_length=255, null=True)),
                ('dns', models.TextField(blank=True, help_text='Описание (вместо description)', null=True)),
                ('code_1', models.CharField(blank=True, help_text='Код 1 - обычно revision', max_length=100, null=True)),
                ('code_2', models.CharField(blank=True, help_text='Код 2 - обычно type', max_length=100, null=True)),
                ('code_3', models.CharField(blank=True, help_text='Код 3 - обычно unitOfMeasure', max_length=100, null=True)),
                ('cipher', models.CharField(blank=True, max_length=100, null=True)),
                ('code_4', models.CharField(blank=True, max_length=100, null=True)),
                ('code_5', models.CharField(blank=True, max_length=100, null=True)),
                ('deletion_mark', models.BooleanField(default=False)),
                ('group_indicator', models.CharField(blank=True, max_length=100, null=True)),
                ('lkn', models.CharField(blank=True, max_length=100, null=True)),
                ('modification_code', models.CharField(blank=True, max_length=100, null=True)),
                ('object_type_code', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_record_id', models.IntegerField(blank=True, null=True)),
                ('position_code', models.CharField(blank=True, max_length=100, null=True)),
                ('position_in_staff_structure_type', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_data', models.TextField(default='{}', help_text='Дополнительные данные в JSON формате')),
                ('sent_to_atom', models.BooleanField(default=False)),
            ],
        ),
    ]
