# Generated by Django 5.2 on 2025-04-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_nomenclature_effective_date_nomenclature_is_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lsi',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lsi',
            name='name',
        ),
        migrations.AddField(
            model_name='lsi',
            name='cipher',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Шифр'),
        ),
        migrations.AddField(
            model_name='lsi',
            name='code_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код1'),
        ),
        migrations.AddField(
            model_name='lsi',
            name='code_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код2'),
        ),
        migrations.AddField(
            model_name='lsi',
            name='code_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код3'),
        ),
        migrations.AddField(
            model_name='lsi',
            name='code_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код4'),
        ),
        migrations.AddField(
            model_name='lsi',
            name='code_5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код5'),
        ),
        migrations.AddField(
            model_name='lsi',
            name='deletion_mark',
            field=models.BooleanField(default=False, verbose_name='ПометкаУдаления'),
        ),
        migrations.AddField(
            model_name='lsi',
            name='dns',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dns'),
        ),
        migrations.AddField(
            model_name='lsi',
            name='drawing_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='НомерЧертежа'),
        ),
        migrations.AddField(
            model_name='lsi',
            name='group_indicator',
            field=models.BooleanField(default=False, verbose_name='ПризнакГруппы'),
        ),
        migrations.AddField(
            model_name='lsi',
            name='lkn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Лкн'),
        ),
        migrations.AddField(
            model_name='lsi',
            name='modification_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='КодМодификации'),
        ),
        migrations.AddField(
            model_name='lsi',
            name='object_type_code',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='КодТипаОбъекта'),
        ),
        migrations.AddField(
            model_name='lsi',
            name='parent_record_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ИдентификаторРодительскойЗаписи'),
        ),
        migrations.AddField(
            model_name='lsi',
            name='position_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='КодПозиции'),
        ),
        migrations.AddField(
            model_name='lsi',
            name='position_in_staff_structure_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ПозицияВШтатнойСтруктуреТипа'),
        ),
        migrations.AddField(
            model_name='lsi',
            name='position_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='НаименованиеПозиции'),
        ),
        migrations.AddField(
            model_name='lsi',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='lsi',
            name='specialty',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='lsi',
            name='uuid',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='УУИД'),
        ),
    ]
