# Generated by Django 5.2 on 2025-04-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_lsi_description_remove_lsi_name_lsi_cipher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomenclature',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='nomenclature',
            name='type_of_nomenclature',
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='ПризнакАрхивнойЗаписи'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='checksum',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='КонтрольнаяСуммаЗаписи'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='classifier_unique_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='УникальныйКодКлассификатора'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='deletion_mark',
            field=models.BooleanField(default=False, verbose_name='ПометкаУдаления'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='spk_nomenclature_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='СПК_ВидНоменклатуры'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Аббревиатура'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='cipher',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Шифр'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='drawing_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ЧертежныйНомер'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='ДатаВведенияВДействие'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='ekps_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='КодЕКПС'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='НаименованиеПолное'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='internal_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='КодВнутренний'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='kvt_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='КодКВТ'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='НаименованиеКраткое'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='uuid',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='УУИД'),
        ),
    ]
