# Generated by Django 5.2 on 2025-04-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MappingField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(choices=[('ATOM', 'ATOM'), ('TEAMCENTER', 'TeamCenter'), ('INTBUS', 'IntBus')], max_length=50, verbose_name='Система-источник')),
                ('target_system', models.CharField(choices=[('ATOM', 'ATOM'), ('TEAMCENTER', 'TeamCenter')], max_length=50, verbose_name='Целевая система')),
                ('data_type', models.CharField(choices=[('nomenclature', 'Номенклатура'), ('lsi', 'ЛСИ (Логическая структура изделия)')], max_length=50, verbose_name='Тип данных')),
                ('source_field', models.CharField(max_length=255, verbose_name='Поле источника')),
                ('target_field', models.CharField(max_length=255, verbose_name='Поле назначения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Правило маппинга',
                'verbose_name_plural': 'Правила маппинга',
                'unique_together': {('source_system', 'target_system', 'data_type', 'source_field', 'target_field')},
            },
        ),
    ]
